# Propagates public/tools/flipbook-template.html (the flipbook viewer source
# of truth) into its two consumers:
#   1. FLIPBOOK_TPL_B64 inside public/tools/book-studio.html  (new books)
#   2. src/lib/flipbook-viewer-template.ts                    (reader-route
#      upgrade of legacy hosted books)
# Run after every edit to the template:  powershell -File scripts/embed-flipbook-template.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$tplPath = Join-Path $root "public\tools\flipbook-template.html"
$studioPath = Join-Path $root "public\tools\book-studio.html"
$tsPath = Join-Path $root "src\lib\flipbook-viewer-template.ts"

$b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($tplPath))

# 1. studio
$studio = [IO.File]::ReadAllText($studioPath)
$pattern = 'const FLIPBOOK_TPL_B64="[^"]*";'
if ($studio -notmatch $pattern) { throw "FLIPBOOK_TPL_B64 not found in book-studio.html" }
$studio = [regex]::Replace($studio, $pattern, { param($m) 'const FLIPBOOK_TPL_B64="' + $b64 + '";' })
[IO.File]::WriteAllText($studioPath, $studio, (New-Object System.Text.UTF8Encoding($false)))

# 2. reader-route module
$ts = @"
// AUTO-GENERATED by scripts/embed-flipbook-template.ps1 - do not edit by hand.
// Source of truth: public/tools/flipbook-template.html
// Placeholders: __TITLE__ __PAGES__ __RTL__ __LANG__
const FLIPBOOK_VIEWER_TEMPLATE_B64 =
  "$b64";

export function flipbookViewerTemplate(): string {
  return Buffer.from(FLIPBOOK_VIEWER_TEMPLATE_B64, "base64").toString("utf8");
}
"@
[IO.File]::WriteAllText($tsPath, $ts, (New-Object System.Text.UTF8Encoding($false)))

Write-Output "embedded template (b64 length $($b64.Length)) into book-studio.html and flipbook-viewer-template.ts"
